"""change price to float

Revision ID: 4ed1be62778d
Revises: 
Create Date: 2024-10-15 23:32:08.053659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed1be62778d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'price',
               existing_type=sa.DOUBLE(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'price',
               existing_type=sa.Float(),
               type_=sa.DOUBLE(),
               existing_nullable=False)
    # ### end Alembic commands ###
